### PR TITLE
Christol/issue#68

### PR DESCRIPTION
**Pull request by christorange**
- Fixed scroll bar position #68 
- Matched contact info page style to design

### CODE REVIEW

**Comment by IanSaucy** [comment]
@christorange It appears that there are now double scroll bars, any idea why this is happening?

**Comment by christorange** [comment]
Could you provide information of your browser or setting of reproducing this? I see only one vertical scroll bar in both chrome and firefox 

image

**Comment by IanSaucy** [comment]
I'm getting it on both Firefox and Chrome desktop when I shrink the window to be shorter than required for full content display. I don't see it on mobile.

image

**Comment by christorange** [comment]
I think it's fixed now

**Comment by IanSaucy** [comment]
Looks like it fixed

**Pull request merged**
